# 3、Numpy的ndarray的一维，二维的操作，常用属性，形状调整，与python list的互相转换

## ndarray和list的互相转换

In [5]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))
oneArray = np.array(list1)
print(type(oneArray))  #类型是ndarray
print(oneArray)

[1, 2, 3, 4]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [4]:
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


## 常用属性

In [3]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int64


## 调整数组的形状

In [6]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four)
four1 = four
print(id(four))
four.shape = (3, 2)  # 改变形状
# shape修改的是原有的
print(id(four))
print(id(four1))
print(four)
print('-' * 50)
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

[[1 2 3]
 [4 5 6]]
1648191457296
1648191457296
1648191457296
[[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
1648191457296
1648191455376


array([[1, 2, 3],
       [4, 5, 6]])

## 一维、二维操作

In [11]:
# 将多维变成一维数组
five = four.reshape((6,), order='C')
print(five)
print('-' * 50)
five = four.reshape((6,), order='F')
print(five)
print('-' * 50)
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten()  # 展开成一维数组
print(six)

[1 2 3 4 5 6]
--------------------------------------------------
[1 3 5 2 4 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [17]:
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1


In [18]:
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [20]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [19]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4
